### ISSUE TITLE
All artworks with thumbnails do not really have an image on the website

### ISSUE THREAD

**Issue by mitar** [MuseumofModernArt/collection#29]
When I link to a website I would expect that artworks with thumbnails have an image on the website. But this does not seem to be so. There are artworks which have thumbnails but do not have images. Examples (I can provide full list if needed):

* https://www.moma.org/collection/works/9
  * https://www.moma.org/media/W1siZiIsIjE0OSJdLFsicCIsImNvbnZlcnQiLCItcmVzaXplIDMwMHgzMDBcdTAwM2UiXV0.jpg?sha=e57fc281da1e6a83
* https://www.moma.org/collection/works/50
  * https://www.moma.org/media/W1siZiIsIjI4OTExNCJdLFsicCIsImNvbnZlcnQiLCItcmVzaXplIDMwMHgzMDBcdTAwM2UiXV0.jpg?sha=9bdec4b6fe84ea57
* https://www.moma.org/collection/works/54
  * http://www.moma.org/media/W1siZiIsIjM0OCJdLFsicCIsImNvbnZlcnQiLCItcmVzaXplIDMwMHgzMDBcdTAwM2UiXV0.jpg?sha=4a7ba2ec36104db6

Could this be brought in sync?

And that opens also the opposite question: are there artworks which do have images but do not have thumbnails in the dataset?

**Comment by clinejj** [comment]
This should be updated with the latest version. Because some of the artworks in the collection change status on whether they can be included in this dataset (or our permissions for the image), older versions of the data may have this information out of sync. We plan to update this dataset more frequently going forward, which should keep this closer in line.
