### ISSUE TITLE
Thumbnails are for old versions of images

### ISSUE THREAD

**Issue by mitar** [MuseumofModernArt/collection#30]
Some works have thumbnails which are for old versions of digitized images of works. Example:

https://www.moma.org/collection/works/2

Which in the dataset has thumbnail:
![](https://www.moma.org/media/W1siZiIsIjU5NDA1Il0sWyJwIiwiY29udmVydCIsIi1yZXNpemUgMzAweDMwMFx1MDAzZSJdXQ.jpg?sha=137b8455b1ec6167) (https://www.moma.org/media/W1siZiIsIjU5NDA1Il0sWyJwIiwiY29udmVydCIsIi1yZXNpemUgMzAweDMwMFx1MDAzZSJdXQ.jpg?sha=137b8455b1ec6167)

But a comparable thumbnail size of the new version of a digitized image looks like:
![](https://www.moma.org/media/W1siZiIsIjUyNzc3MCJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDI3MngxNjhcdTAwM2UiXV0.jpg?sha=de1bbae3ef278e8f) (https://www.moma.org/media/W1siZiIsIjUyNzc3MCJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDI3MngxNjhcdTAwM2UiXV0.jpg?sha=de1bbae3ef278e8f)

Could those thumbnails be updated?

**Comment by mrtngrsbch** [comment]
Hello,
Let me take advantage of the topic to ask: 
- How to determine the size of the thumbnail?
- What would be the size (standard ?) of a thumbnail to 'respect' a copyrighted work?

**Comment by mitar** [comment]
Currently thumbnails are max 300x300 in size.

**Comment by mrtngrsbch** [comment]
Sorry to ask again...
Is there an explicit rule for this size or is it a courtesy convention?
I am not only asking this question for MoMA but in general terms. In my repository I consider a 1024px image as a preview.
I would like to know the general consensus so that I can adapt better.
thanks a lot

**Comment by mitar** [comment]
Maybe read [about picture element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture).

**Comment by clinejj** [comment]
Because of the update frequency of the script, it's possible the image may be out of date when compared to what's on the website. The latest release should have the most up to date images, and we have increased the frequency to weekly instead of monthly. We've also updated the image size, now under the column `ImageURL` instead of `ThumbnailURL`, which has a larger image.
